name: CMake on Mac/Linux/Windows platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered
      # for all matrix combinations. Consider changing this to true
      # when your workflow is stable.
      fail-fast: false

      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest ]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v6
    - run: |
        date > generated.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m
    - uses: actions/setup-python@v6
    - run: pip install habanero PyQt5 python-poppler-qt5 feedparser         
