name: CMake on Mac/Linux/Windows platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    #- cron: '0 0 * * *'  # Once per day
    - cron: '0 0 2-30/2 * *' # Once per day

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    strategy:
      fail-fast: false

      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest ]
        os: [ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v6
    - run: |
        date > generated.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "gitbot on `date`"
        git push
    - uses: actions/setup-python@v6
    - run: |
          sudo apt update 
          # sudo apt install --yes python3-poppler-qt5
          pip install --upgrade pip
          pip install --upgrade sip
          pip install git+https://github.com/frescobaldi/python-poppler-qt5.git
          pip install habanero PyQt5 feedparser python3-poppler-qt5 
          pip install -e .
